assignment('s2', 1).
assignment('t2', 0).
assignment('t5', 0).
assignment('t4', 0).
assignment('s3', 0).
assignment('s1', 2).
assignment('t6', 0).
assignment('t1', 2).
assignment('t3', 2).
assignment('nb2', 2).
assignment('q1', 0).
assignment('q5', 1).
assignment('nb1', 0).
assignment('q2', 0).
assignment('q4', 0).
assignment('q3', 0).
assignment('b1', 1).
assignment('p1', 0).
assignment('p3', 1).
assignment('p2', 0).
